### ISSUE TITLE
[EPIC] Add user warnings and tidy up documentation

### ISSUE THREAD

**Issue by emmalu** [developmentseed/lonboard#309]
## Context
All users need proper documentation, especially in times of possible errors due to edge-cases or improper use of the library they are using. We can use this opportunity of building up the documentation within `lonboard` to explore its functionality and get familiar with the code we are contributing to.

## Issue
We need to add warnings and feedback at times when users may hit expected (or unexpected) limitations.

## Acceptance-Criteria
List the tasks that need to be completed or artifacts that need to be produced
- [ ] https://github.com/developmentseed/lonboard/issues/293
- [ ] https://github.com/developmentseed/lonboard/issues/282
- [ ] https://github.com/developmentseed/lonboard/issues/131
- [ ] https://github.com/developmentseed/lonboard/issues/146
- [ ] https://github.com/developmentseed/lonboard/issues/204
