### ISSUE TITLE
[EPIC] Improved map defaults

### ISSUE THREAD

**Issue by emmalu** [developmentseed/lonboard#310]
## Context
We can improve some of the user's experience by default.

## Issue
We should complete the following UI enhancements.

## Acceptance-Criteria
These are the tasks that need to be completed or artifacts that need to be produced.

- [x] https://github.com/developmentseed/lonboard/issues/281
- [x] https://github.com/developmentseed/lonboard/issues/247
- [ ] https://github.com/developmentseed/lonboard/issues/203

**Comment by kylebarron** [comment]
Closing with https://github.com/developmentseed/lonboard/pull/330. It's not clear whether the layer control should be a default behavior in `viz`. That can be a separate discussion
