### ISSUE TITLE
[EPIC] Javascript enhancements

### ISSUE THREAD

**Issue by emmalu** [developmentseed/lonboard#313]
## Context
Interactive maps need to be reactive in any and all environments. 

## Issue
Let's implement some JS-based improvements.

## Acceptance-Criteria
These are the tasks that need to be completed or artifacts that need to be produced.
- [ ] https://github.com/developmentseed/lonboard/issues/148
- [ ] https://github.com/developmentseed/lonboard/issues/264
- [ ] https://github.com/developmentseed/lonboard/issues/112

**Comment by kylebarron** [comment]
#148 is probably the most powerful feature here and is what I'd focus on, even though it has a bit of a learning curve, in particular to figure out how to draw the bounding box. 

#264 is a bit of an unknown. I don't really know what the necessary parts of it are. 

#112 was prototyped in https://github.com/developmentseed/lonboard/pull/113 but it looks like it might have too much overhead and performance impact, at least in the way I was testing.
