### ISSUE TITLE
[EPIC] Add Google Maps JS API vector map option

### ISSUE THREAD

**Issue by ryanbaumann** [developmentseed/lonboard#454]
## Context
Offer developers the flexibility to choose another map, such as a Google Map, provided the map SDK supports native Deck.gl layers as the [deck.gl and Google Maps Platform JS API does](https://deck.gl/docs/developer-guide/base-maps/using-with-google-maps): 
* [Google Maps JS API / deck.gl example](https://developers.google.com/maps/documentation/javascript/examples/deckgl-arclayer)
* ![image](https://github.com/developmentseed/lonboard/assets/4342845/e3ca0f70-07cd-419f-b453-eb6cf23d0bf0)

## Issue
This would require:

1. Instantiating the map using Google Maps JS API vs. MapLibre GL JS
2. Updating any UI bindings tightly coupled to the Maplibre GL  e.g. placing legends, map controls, etc on the Map div.
3. Adding a developer option for the user to bring their own API access key and map id instead of just hard-coded map styles in https://github.com/developmentseed/lonboard/blob/main/lonboard/basemap.py
4. Other considerations - please add additional details / risks here

## Acceptance-Criteria
The tasks that need to be completed or artifacts that need to be produced:
- [ ] Determine feasibility and alignment with repo owners
- [ ] Mock up the API design and options, get feedback from repo owners
- [ ] Create PR with map options and updates, tests, release notes
- [ ] Review and merge

**Comment by kylebarron** [comment]
Hey Ryan, thanks for the issue.

This chart from the deck docs shows that there are 10 different basemap combinations:
<img width="669" alt="image" src="https://github.com/developmentseed/lonboard/assets/15164633/bdf787ef-9f38-475d-9223-d07bce3be80c">

It's not clear to me how many of these Lonboard should try to integrate with.

There's been some discussion recently (https://github.com/developmentseed/lonboard/discussions/442, https://github.com/developmentseed/lonboard/pull/437) of whether Lonboard should be less tied to _any_ basemap. In the sense of: to enable things like multiple views and alternate map projections, we don't want to tie ourselves too closely to Maplibre by using MapboxOverlay. But connecting to the Google Maps API ties us to another mast, and it's not clear if it's worth the engineering and maintenance burden at this point.

And then there are the technical questions of actually implementing the integration. I've never used the Google Maps API so it would take time to figure out the integration. And should we load every basemap library for every Python user?

**Comment by ryanbaumann** [comment]
Great discussion @kylebarron. I wasn't aware of some of the limitations of the [custom style layer](https://maplibre.org/maplibre-gl-js/docs/examples/custom-style-layer/) limitations with Dec and MapLibre/Mapbox e.g. projections, some events, etc. I also agree that it's not obvious where Lonboard as a viz framework in Python should draw the line for support with various map rendering SDKs.

It sounds like there's a need to separate concerns between the visualization context of Lonboard viz with other background scenes like a map renderer e.g. Maplibre, Mapbox, Google Maps JS API. An abstraction layer right now doesn't exist that works across Map SDK. and likely would be complicated to support as each flavor of Map Rendering SDK has different developer interfaces.  

Given that I agree that this is likely not feasible. The workaround that's more feasible and likely "good enough" would be supporting ZXY raster tile layers as a Maplibre source for the base map. That would have downsides as a raster vs. vector map data format, but would provide flexibility for developers that need to reference a specific base map (even for a bespoke use case like a construction job site)

**Comment by kylebarron** [comment]
> The workaround that's more feasible and likely "good enough" would be supporting Z/X/Y raster tile sources as a Maplibre raster source for a Lonboard viz base map.

This already exists when rendered by deck https://developmentseed.org/lonboard/latest/api/layers/bitmap-tile-layer/

It would be better to use Maplibre in some instances where you want to put the raster below labels. An advanced user can do this themselves by modifying the Maplibre Style JSON
